### ISSUE TITLE
Use lazy evaluation for key generation

### ISSUE THREAD

**Issue by jeffreyyoungs-vgs** [xhost-cookbooks/openvpn#100]
You already use _unless_...
```
# Use unless instead of not_if otherwise OpenSSL::PKey::DH runs every time.
unless ::File.exist?("#{key_dir}/dh#{key_size}.pem")
```

But when I wrap the cookbook and have my own key process, this still runs at converge time on the first run unnecessarily. If you use the recommended key size (4096) this is extremely painful. 

My workaround was to send a key size smaller than I'm actually using (side-effects unknown), but lazy evaluation should deal with this nicely. 

https://docs.chef.io/resource_common.html#lazy-evaluation

**Comment by flaccid** [comment]
This one got through in recent commits by stealth. @jeffreyyoungs-vgs please test with master and re-open if any issues.
