### ISSUE TITLE
Do you need help maintaining this repository?

### ISSUE THREAD

**Issue by josegonzalez** [xhost-cookbooks/openvpn#39]
I'd be happy to pitch in and clean up some of the issues/pull requests, as well as implement them in a way that doesn't break CI in cases where they currently do.

**Comment by eherot** [comment]
Just to be clear (since we are now over a year since the last release of any kind), are you hoping to fix the backwards compatibility issues before making the next release or is there something else that we are waiting for (something that I or someone else could potentially help with)?

**Comment by josegonzalez** [comment]
Closing this issue. My PR wasn't merged (and tests are just fundamentally broken because berk berk berk :P) and I was not directly responded to. I've since moved to using pritunl (which is nice) though it would still be nice to get movement on this repo, even if for the benefit of the chef community at large.

Good luck to those using this in production!

**Comment by flaccid** [comment]
@josegonzalez you may be pleased to see that we have made quite a bit of progress since your last comment. Its in a much better state for contributions, testing has been updated and we're ready for more pulls and issues :)

**Comment by josegonzalez** [comment]
Thats nice, hopefully that stays the case for future users of this cookbook. As I mentioned before, I have since moved to Pritunl, which works quite nicely for my use case.

Thanks for your hard work though!

**Comment by ascendantlogic** [comment]
There have (as of this writing) been 181 commits to master since the last release. Is there a reason new releases have not been made? I'm just curious because I'd really rather not have to fork and freeze as a method of capturing the more recent changes.

**Comment by flaccid** [comment]
@ascendantlogic we just need to complete https://github.com/xhost-cookbooks/openvpn/milestones/v3 before we tag a new major release, v3.0.0.
