### ISSUE TITLE
Setting ["openvpn"]["routes"] in role override_attributes doesn't set routes

### ISSUE THREAD

**Issue by williamsjj** [xhost-cookbooks/openvpn#46]
```
{
  "name": "openvpn-server",
  "default_attributes": {
  },
  "json_class": "Chef::Role",
  "run_list": [
    "recipe[openvpn::default]",
    "recipe[openvpn::users]"
  ],
  "description": "OpenVPN Server",
  "chef_type": "role",
  "override_attributes": {
      "openvpn" : {
          "config" : {
              "local" : "0.0.0.0",
          },
          "gateway" : "gw.example.com",
          "subnet" : "192.168.0.0",
          "netmask" : "255.255.0.0",
          "routes" : [
              "push 'route 1.2.3.0 255.255.255.224'"
          ],
          "script_security" : "2",
      }
  }
}
```

No push routes show up in server.conf.

**Comment by mhalligan** [comment]
There's nothing in the cookbook that actually reads the routes keys. The server.conf template only addresses hash elements under ["openvpn"]["conf"]. You might try putting your configurations under that tree. I gave up and duckpatched the template to basically be a static configuration file.

**Comment by flaccid** [comment]
Now fixed, https://github.com/xhost-cookbooks/openvpn/commit/9aaa5d2cc5b3a5681c56ff305380d4fce7e7f693.
Please re-open if needed.
