### ISSUE TITLE
berks cookbook does not  download the latest version of openvpn

### ISSUE THREAD

**Issue by chrisduong** [xhost-cookbooks/openvpn#47]
Hi,
My berksfile is:
`
source "https://supermarket.chef.io"

metadata

cookbook 'openvpn', '~> 2.1.0'
`

However, during berks install I don't have the latest template file: server.conf.erb. 
I logged into my test kitchen, it is a different file

`
# OpenVPN server config file
#
# Generated by Chef - local changes will be overwritten

port <%= @port %>
proto <%= @proto %>
<% if @type == "server-bridge" -%>
dev tap<%= @interface_num %>
<% else -%>
dev tun<%= @interface_num %>
`
The problem with this old file is  that if the 'plugins' is empty as default, it would bring the error - Nomethod each for Nil:NilClass 
`
<% @plugins.each do |p| -%>
plugin <%= p %>
`
<% end -%>

**Comment by flaccid** [comment]
@chrisduong  as you probably would of noticed the config file is now dynamically configured in the master branch, see https://github.com/xhost-cookbooks/openvpn/blob/master/templates/default/server.conf.erb.
I added in a Rakefile and a few more little enhancements to help with testing.
