### ISSUE TITLE
"users bags"

### ISSUE THREAD

**Issue by zackp30** [xhost-cookbooks/openvpn#64]
I'm very new to Chef (started yesterday) and I'm wondering what the parameters to the `knife` tool to create the user data bags, I've tried the following combinations:

- users (data bag), openvpn (data bag item)
- openvpn (data bag), users (item)
- users (data bag), zack (item)

Is there something I'm missing?

**Comment by zackp30** [comment]
Oh, I forgot to say that it's not working as in the certificates are not being generated.

**Comment by zackp30** [comment]
Thanks to cheeseplus at IRC for helping me, `openvpn::users` is the role to be used because `openvpn` defaults to `openvpn::default`. :smile:

**Comment by vskubriev** [comment]
If you need ldap users. You can see my small thin forks at github. It is
very useful for me.
18.08.2015 18:12 пользователь "Zack Piper" <notifications@github.com>
написал:
