### ISSUE TITLE
Please upload to supermarket.

### ISSUE THREAD

**Issue by ohlol** [xhost-cookbooks/openvpn#72]
Hi, the most recent version of this cookbook on supermarket is 2.1.0. Can you please update?

**Comment by jperville** [comment]
+1

**Comment by flaccid** [comment]
Not until the v3 milestone is complete https://github.com/xhost-cookbooks/openvpn/milestones.
Feel free to contribute!

**Comment by jperville** [comment]
Thanks @flaccid, looking forward to v3 then :)
