### ISSUE TITLE
IP Forwarding setup 

### ISSUE THREAD

**Issue by gsaslis** [xhost-cookbooks/openvpn#76]
Hi guys, 

I noticed there's an `enable_ip_forwarding` recipe which is not yet documented in the `README.md` which seems to help me achieve the same (?) thing as using the server.up script does?

In particular I see this recipe sets the `net.ipv4.conf.all.forwarding` and `net.ipv6.conf.all.forwarding` using the sysctl_param resource. The up script, if used, sets `/sbin/sysctl -w net.ipv4.ip_forward=1`, so I am somewhat unsure as to which method is the preferred one to use here.. ? 

If someone could help explain this, I'd be happy to tidy it up in a PR that helps document this. 

Thanks!

**Comment by flaccid** [comment]
The server recipe includes the `enable_ip_forwarding` recipe to ensure IP forwarding is enabled but also so it's managed on a chef resource level in terms of persistence (too). The `server.up` script ensures its turned on when the script is run on the system level (there is somewhat a portability case here where this is not dependent on the chef cookbook but more a generic choice). One shouldn't rely on the other and there is no harm in doing it in both places.

As its just a trivial recipe included by a main recipe, there may not be any need to document in the readme, but no probablem if you'd like to submit a PR for the it on any of the above. Hope this kind of helps :)
