### ISSUE TITLE
differences between 2.1.0 and 2.1.1 are breaking changes!

### ISSUE THREAD

**Issue by willejs** [xhost-cookbooks/openvpn#77]
There are major changes in 2.1.1 that are not backwards compatible with 2.x. The structure of the recipes in the cookbook, and also the routes attribute changes to push_routes. This is a breaking change.
Therefore the cookbook should be 3.x and follow semver.

**Comment by flaccid** [comment]
That's totally the plan. Feel free to flag any structural changes for v3 milestone, https://github.com/xhost-cookbooks/openvpn/milestones/v3.
