### ISSUE TITLE
Support for OpenVZ servers

### ISSUE THREAD

**Issue by brauliobo** [xhost-cookbooks/openvpn#79]
/var/log/openvpn.log
```
  1 Sat Apr  2 21:59:54 2016 OpenVPN 2.3.2 i686-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014
  2 Sat Apr  2 21:59:54 2016 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
  3 Sat Apr  2 21:59:54 2016 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)
  4 Sat Apr  2 21:59:54 2016 Exiting due to fatal error
```

Possible solutions:
http://wiki.vpslink.com/TUN/TAP_device_with_OpenVPN_or_Hamachi
http://wiki.openvz.org/VPN_via_the_TUN/TAP_device

**Comment by flaccid** [comment]
@brauliobo do any of the possible solutions work, e.g. `modprobe tun` ?

**Comment by brauliobo** [comment]
@flaccid no it didn't... seems I need permission from the hosting provider, asked them, let's see if it works then

**Comment by brauliobo** [comment]
will close this for now. this cookbook could at most check the device, create it if it doesn't exist and check if it is functional
