### ISSUE TITLE
Install dependency libengine-pkcs11-openssl

### ISSUE THREAD

**Issue by brauliobo** [xhost-cookbooks/openvpn#80]
I've noticed after struggling to install openvpn with this cookbook on a debian jessie that `/etc/openvpn/keys/openssl.cnf` refers to `/usr/lib/engines/engine_pkcs11.so` but this file doesn't exist. So probably `libengine-pkcs11-openssl` package needs to be installed too

**Comment by flaccid** [comment]
The `rake` usage needs to be deprecated, see https://github.com/xhost-cookbooks/openvpn/issues/23#issuecomment-68737485. I have created https://github.com/xhost-cookbooks/openvpn/issues/83 to address this.

For now install https://packages.debian.org/jessie/rake and https://packages.debian.org/jessie/libengine-pkcs11-openssl using something like https://github.com/xhost-cookbooks/system#systeminstall_packages or via your own method with the `package` resource.

Server installation with jessie seems ok at the moment. I have added it to the readme as supported https://github.com/xhost-cookbooks/openvpn/commit/ddd91e1a5a0da988ae6706331658a47d2935c20d.
