### ISSUE TITLE
Firewall and gateway options needed by default?

### ISSUE THREAD

**Issue by brauliobo** [xhost-cookbooks/openvpn#81]
1) I needed to add `iptables -t nat -A POSTROUTING -o br0 -j MASQUERADE` to `/etc/openvpn/server.up.d/postrouting.sh`. Without this no packets were forwarded from the tunnel to the internet. I've noticed also that digitalocean tutorials create similar rules using ufw (https://www.digitalocean.com/community/tutorials/how-to-set-up-an-openvpn-server-on-debian-8)

2) When starting the client from command line `sudo openvpn --config user.ovpn` it was necessary to add `push "redirect-gateway def1 bypass-dhcp"` to `server.conf`, otherwise it won't completely create the necessary routes on the client. With network-manager it creates the routes anyway.

**Comment by Zugschlus** [comment]
(1) Having NAT as default would be bad since VPN links can be used in internal networks or with globally routable IP addresses as well. You get to decide what you need to have your network running. In your case NAT seems necessary.

**Comment by flaccid** [comment]
Not supported in the cookbook at this time, see https://github.com/xhost-cookbooks/openvpn/blob/master/README.md#not-supported. However, we would consider contrib of functionality to assist this kind of config.
