### ISSUE TITLE
Unable to run include_recipe 'openvpn::server'

### ISSUE THREAD

**Issue by mrlamroger** [xhost-cookbooks/openvpn#84]
```
[2016-05-30T00:52:24+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2016-05-30T00:52:24+00:00] ERROR: could not find recipe server for cookbook openvpn
==> default: [2016-05-30T00:52:24+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```
I can work around it by specifying the type as `server` and running `include_recipe 'openvpn'` instead

**Comment by zivagolee** [comment]
I am seeing this too. I am not sure what is going on but when I do a fork of this repo and then point Berksfile to it, I can run `include_recipe 'openvpn::server'` just fine.

**Comment by mrlamroger** [comment]
master is on 2.1.1 while supermarket is on 2.1.0

2.1.0 only has the generic default recipe. https://github.com/xhost-cookbooks/openvpn/tree/v2.1.0

**Comment by flaccid** [comment]
There wont be anymore releases for v2. We do need contributors for https://github.com/xhost-cookbooks/openvpn/milestones/v3. Use of the server recipe works fine in master.
