### ISSUE TITLE
Recommended method of revoking users?

### ISSUE THREAD

**Issue by TemporarilyOffline** [xhost-cookbooks/openvpn#89]
Thanks for providing the cookbook to create a VPN server.  I don't see anything in the documentation about how to revoke users.  I also don't see the `revoke-full` command on the server to do it according to the "OpenVPN way".  

What is the recommended way of removing users access to the VPN?

Ideally I'd like to remove the user, manually run chef on the server and have it boot that user from the connection.

Thanks!

**Comment by flaccid** [comment]
I believe we are still looking for contribution in this area.
There is some related history:
- https://github.com/xhost-cookbooks/openvpn/pull/25
- https://github.com/xhost-cookbooks/openvpn/pull/82
- https://github.com/xhost-cookbooks/openvpn/issues/66

Would love to see a pull request including documentation in the readme on usage.

**Comment by flaccid** [comment]
https://github.com/xhost-cookbooks/openvpn/issues/55 is also related.

**Comment by flaccid** [comment]
`revoke-full` is in easy-rsa (https://github.com/OpenVPN/easy-rsa-old/blob/master/easy-rsa/2.0/revoke-full). Created https://github.com/xhost-cookbooks/openvpn/issues/90 to begin.
