### ISSUE TITLE
possible to allow to override the template file for `user client conf`

### ISSUE THREAD

**Issue by chrisduong** [xhost-cookbooks/openvpn#93]
Hi,

I have a need for adding one more config for our user client conf, called `tls-auth 'ta.key' 1`.

But it is not feasible to rewind Chef Resources, since the "user create code" lives inside a Search loop which yields different **user id**.

Is it possible if we can add **cookbook attributes** to the template file like this.

```
%w(conf ovpn).each do |ext|
      template "#{node['openvpn']['key_dir']}/#{node['openvpn']['client_prefix']}-#{u['id']}.#{ext}" do
        source 'client.conf.erb'
        cookbook node['openvpn']['client_template_cookbook']
        variables(client_cn: u['id'])
      end
    end
```

**Comment by flaccid** [comment]
That might be feasible. I'd be keen to see how a pull request for it might look (with documentation).

**Comment by chrisduong** [comment]
Hi,

Please take a look at PR #95

**Comment by flaccid** [comment]
Closing as PR #95 was merged.
